sonar.projectKey=zedsas
sonar.organization=zedsas
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/*.sh,**/*.sql,**/*.md,**/.github/**,libs/**
sonar.sourceEncoding=UTF-8